"""
Metadata management for KnowledgeMCP.

Each file in knowledge/ has a JSON sidecar at:
  knowledge/.knowledge_meta/<relative_path>.json

Metadata is created lazily on first access and updated by explicit index calls.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from env import CHARS_PER_TOKEN_APPROX, KNOWLEDGE_DIR, KNOWLEDGE_META_DIR


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


@dataclass
class MagicFilter:
    """A named slice of a file, auto-generated by an AI background task."""
    label: str
    start_line: int
    end_line: int
    description: str


@dataclass
class FAQ:
    """A pre-analyzed question-answer pair extracted from a knowledge file."""
    question: str
    answer: str


@dataclass
class MetaRecord:
    """Full metadata record for a single knowledge file."""
    summary: str = ""
    token_count: int = 0
    created_at: str = ""
    file_type: str = ""
    magic_filters: list[MagicFilter] = field(default_factory=list)
    faqs: list[FAQ] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _meta_path(rel_path: str) -> Path:
    """Return the sidecar JSON path for a given relative file path."""
    return KNOWLEDGE_META_DIR / f"{rel_path}.json"


def _ensure_meta_dir(meta_file: Path) -> None:
    meta_file.parent.mkdir(parents=True, exist_ok=True)


def _estimate_tokens(file_path: Path) -> int:
    try:
        size = file_path.stat().st_size
        return max(1, size // CHARS_PER_TOKEN_APPROX)
    except OSError:
        return 0


def _file_mtime_iso(file_path: Path) -> str:
    try:
        ts = file_path.stat().st_mtime
        return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()
    except OSError:
        return ""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_meta(rel_path: str) -> MetaRecord:
    """Load metadata for a file, creating it from filesystem stats if missing."""
    sidecar = _meta_path(rel_path)
    if sidecar.exists():
        try:
            raw = json.loads(sidecar.read_text(encoding="utf-8"))
            magic_filters = [
                MagicFilter(**mf) for mf in raw.get("magic_filters", [])
            ]
            faqs = [
                FAQ(**f) if isinstance(f, dict) else f
                for f in raw.get("faqs", [])
            ]
            return MetaRecord(
                summary=raw.get("summary", ""),
                token_count=raw.get("token_count", 0),
                created_at=raw.get("created_at", ""),
                file_type=raw.get("file_type", ""),
                magic_filters=magic_filters,
                faqs=faqs,
            )
        except (json.JSONDecodeError, TypeError, KeyError):
            pass  # Fall through to re-index

    # Auto-create from filesystem
    meta = _index_from_fs(rel_path)
    save_meta(rel_path, meta)
    return meta


def save_meta(rel_path: str, meta: MetaRecord) -> None:
    """Persist a MetaRecord as a JSON sidecar file."""
    sidecar = _meta_path(rel_path)
    _ensure_meta_dir(sidecar)
    data = asdict(meta)
    sidecar.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def index_file(rel_path: str) -> MetaRecord:
    """
    (Re)compute filesystem-derived metadata for a file.
    Preserves existing summary and magic_filters if present.
    """
    existing: MetaRecord | None = None
    sidecar = _meta_path(rel_path)
    if sidecar.exists():
        try:
            existing = get_meta(rel_path)
        except Exception:
            pass

    fresh = _index_from_fs(rel_path)
    if existing is not None:
        # Preserve human/AI-written fields
        fresh.summary = existing.summary
        fresh.magic_filters = existing.magic_filters
        fresh.faqs = existing.faqs

    save_meta(rel_path, fresh)
    return fresh


def _index_from_fs(rel_path: str) -> MetaRecord:
    abs_path = KNOWLEDGE_DIR / rel_path
    return MetaRecord(
        summary="",
        token_count=_estimate_tokens(abs_path),
        created_at=_file_mtime_iso(abs_path),
        file_type=Path(rel_path).suffix.lower() or ".txt",
        magic_filters=[],
        faqs=[],
    )
